main: "EventManager" # file to be requested
version: 1.0
author: _lordBucket
lazy_loading: false # wether this class should be loaded on startup or when first used

dependencies:
  - "UwU.Utils.Map"
  - "UwU.Events.Event"
  - "UwU.Utils.Logger"
  - "UwU.Events.EventConnection"