main: "UserManager" # file to be requested
version: 1.0
author: _lordBucket
lazy_loading: false # wether this class should be loaded on startup or when first used

dependencies: 
  - "UwU.UserManager.User"
  - "UwU.UserManager.Group"
  - "UwU.GroupManager"
  - "UwU.Utils.Map"